# Generated by Django 6.0.6 on 2026-06-09 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sun_evening', 'Kikoni Fellowship'), ('sun_evening', 'Afrostone Fellowship'), ('mon_prayer', 'Nkrukote Fellowship'), ('tue_bible', 'Tuesday Fellowship'), ('wed_youth', 'Lumbox Fellowship'), ('thur_group', 'Uh Mitchelex Felloship'), ('special', 'Sabbath')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('speaker', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('total_attendance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='attendance.servicetype')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('service_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.memberprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.service')),
            ],
            options={
                'ordering': ['-checked_in_at'],
                'unique_together': {('member', 'service')},
            },
        ),
    ]
