# Generated by Django 6.0.6 on 2026-06-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(choices=[('kikoni', 'Kikoni Fellowship'), ('afrostone', 'Afrostone Fellowship'), ('nkrukote', 'Nkrukote Fellowship'), ('tuesday', 'Tuesday Fellowship'), ('lumbox', 'Lumbox Fellowship'), ('mitchelex', 'Uh Mitchelex Fellowship'), ('sabbath', 'Sabbath')], max_length=50, unique=True),
        ),
    ]
